spin_manifest_version = 2

[application]
name = "command-sample"
version = "0.1.0"

[[trigger.command]]
component = "hiwasi"

[component.hiwasi]
source = "csharpwasi.wasm"
# you can now add files, allowed network hosts,
# use the key/value feature.
[component.hiwasi.build]
command = "dotnet build"
